### ISSUE TITLE
Clicking on navigation dot then right arrow throws undefined

### ISSUE THREAD

**Issue by thereisnodeveloper** [thereisnodeveloper/image-carousel#1]
#### Summary
App unusable. 

#### Steps to Reproduce
1. Start/refresh page
2. Click on a navdot
3. Click on right arrow

#### Expected Behavior
Image carousel should switch to the next image( to the right)

#### Actual Behavior
Throws an error

#### Error Messages
navigator.js:142 Uncaught TypeError: Cannot read properties of undefined (reading 'classList')
    at Navigator.toggleSelectedClassNav (navigator.js:142:1)
    at Navigator.moveCarouselAndNav (navigator.js:127:1)
    at HTMLButtonElement.<anonymous> (navigator.js:37:1)

#### Environment
Chrome
Linux

#### Reproduction Frequency
  * Always
  * 
#### Notes
 Add any additional information that might be helpful in debugging the issue, such as:
  * Recently added the 'click to jump feature' and 'interval slide change' features
  * Currently disabled interval slide

**Comment by thereisnodeveloper** [comment]
fixed - string int conversion error
